method: 'dopri5'
train: True
batch_size: 100
num_epochs: 50
num_steps_max: 20
viz: False
device: 'cpu' # gpu not supported as of now
adjoint: True
lr: 1e-3
num_pts_for_intp: 4 # number of points for interpolation